// React/2022-11-4/router-demo/src/views/Author/Author.jsx
import React, { useState, useEffect } from 'react'
import axios from '../../netWork'
import AuthorStyle from './Author.module.scss';
import { Space, Table, Pagination, Button, Modal, Form, Input, message, Popconfirm } from 'antd';
const { Search } = Input;

export default function Author () {
    const columns = [
        {
            title: 'ID',
            dataIndex: 'id',
            key: 'id',
        },
        {
            title: '摄影师',
            dataIndex: 'name',
            key: 'name',
        },
        {
            title: '操作',
            key: 'action',
            render: (_, record) => (
                <Space size="middle">
                    <a onClick={() => showEditModal(record)}>编辑</a>
                    <Popconfirm
                        title="你确定要删除该数据吗？"
                        onConfirm={() => confirm(record)}
                        onCancel={() => cancel()}
                        okText="确定"
                        cancelText="取消"
                    >
                        <a href="#">删除</a>
                    </Popconfirm>
                </Space>
            ),
        },
    ];

    // 表格的数据
    const [data, setDate] = useState([])
    // 页数
    const [pageNum, setPageNum] = useState(1)
    // 条数
    const [pageSize, setPageSize] = useState(7)
    const [total, setTotal] = useState(0)

    // 新增的值
    let [addForm, setAddForm] = useState({})
    // 新增弹窗控制
    const [isAddModalOpen, setIsAddModalOpen] = useState(false);

    // 修改的值
    let [editForm, setEditForm] = useState({})
    let [id, setId] = useState()
    // 修改弹窗控制
    const [isEditModalOpen, setIsEditModalOpen] = useState(false);

    // 搜索的名称
    const [name, setName] = useState('')

    useEffect(() => {
        getData()
    }, [pageNum, name])

    // 获取数据
    const getData = () => {
        axios({
            url: "/author/check",
            method: "get",
            params: {
                name,
                pageNum,
                pageSize
            }
        }).then(res => {
            if (res.code === 200) {
                setDate(res.results)
                setTotal(res.total)
            }
        })
    }

    // 点击出现新增弹窗
    const showAddModal = () => {
        setIsAddModalOpen(true);
    };
    // 新增确定
    const handleAddOk = () => {
        axios({
            url: '/author/add',
            method: 'post',
            data: {
                ...addForm
            }
        }).then(res => {
            if (res.code === 200) {
                message.success('新增成功！')
                getData();
                setIsAddModalOpen(false);
                setPageNum(Math.floor(total / pageSize) + 1)
            }
        })
    }
    // 新增取消
    const handleAddCancel = () => {
        setIsAddModalOpen(false);
    };
    // 新增的值
    const onAddValuesChange = (changedValues, allValues) => {
        setAddForm(allValues)
    }

    // 点击出现修改弹窗
    const showEditModal = (val) => {
        setEditForm(val)
        setId(val.id)
        setIsEditModalOpen(true);
    };
    // 修改确定
    const handleEditOk = () => {
        axios({
            url: '/author/edit',
            method: 'put',
            data: {
                id,
                name: editForm.name
            }
        }).then(res => {
            if (res.code === 200) {
                message.success('编辑成功！')
                getData()
                setIsEditModalOpen(false);
            }
        })
    };
    // 修改取消
    const handleEditCancel = () => {
        setIsEditModalOpen(false);
    };
    // 修改的值
    const onEditValuesChange = (changedValues, allValues) => {
        setEditForm(allValues)
    }

    // 点击删除
    const confirm = (val) => {
        axios({
            url: '/author/delete',
            method: 'delete',
            data: {
                id: val.id
            }
        }).then(res => {
            if (res.code === 200) {
                message.success('删除成功！');
                getData()
                setPageNum(Math.floor(total / pageSize))
            }
        })
    }
    const cancel = () => {
        message.error('取消删除！');
    }

    // 搜索
    const onSearch = (val) => {
        setPageNum(1)
        setName(val)
        getData()
    }
    // 翻页
    const changePage = (page) => {
        setPageNum(page)
    }


    return (
        <div className={AuthorStyle.table}>
            <div className={AuthorStyle.operation}>
                <Button type="primary" onClick={showAddModal}>新增</Button>
                <Search style={{ width: '300px' }}
                    placeholder="搜索"
                    onSearch={onSearch}
                    enterButton
                    allowClear={true}
                />
            </div>
            <Modal title="新增"
                open={isAddModalOpen}
                onOk={handleAddOk}
                onCancel={handleAddCancel}
                destroyOnClose={true}>
                <Form
                    name="basic"
                    labelCol={{
                        span: 8
                    }}
                    wrapperCol={{
                        span: 16
                    }}
                    onValuesChange={onAddValuesChange}
                >
                    <Form.Item
                        label="摄影师"
                        name="name"
                    >
                        <Input />
                    </Form.Item>
                </Form>
            </Modal>
            <Modal title="修改"
                open={isEditModalOpen}
                onOk={handleEditOk}
                onCancel={handleEditCancel}
                destroyOnClose={true}>
                <Form
                    name="basic"
                    labelCol={{
                        span: 8
                    }}
                    wrapperCol={{
                        span: 16
                    }}
                    initialValues={editForm}
                    onValuesChange={onEditValuesChange}
                >
                    <Form.Item
                        label="摄影师"
                        name="name"
                    >
                        <Input />
                    </Form.Item>
                </Form>
            </Modal>
            <Table
                rowKey={(row) => row.id}
                columns={columns}
                dataSource={data}
                pagination={false}
            />
            <div className={AuthorStyle.page}>
                <Pagination
                    current={pageNum}
                    defaultCurrent={pageNum}
                    defaultPageSize={pageSize}
                    total={total}
                    onChange={changePage}
                />
            </div>
        </div>
    )
}

// Vue2/vue-admin-template/src/views/author/index.vue
<template>
    <div class="app-container">
        <div class="wrap">
            <el-button @click="handleAdd">新增</el-button>
            <div class="wrap_content">
                <el-input
                    placeholder="请输入类型名称"
                    v-model="name"
                    clearable
                    @clear="search"
                />
                <el-button type="primary" @click="search">搜索</el-button>
            </div>
        </div>
        <el-table :data="tableData" style="width: 100%">
            <el-table-column prop="id" label="ID"> </el-table-column>
            <el-table-column prop="name" label="作者"> </el-table-column>
            <el-table-column label="操作" width="100">
                <template slot-scope="scope">
                    <el-button @click="handleEdit(scope.row)" type="text"
                        >编辑</el-button
                    >
                    <el-button type="text" @click="handleDelete(scope.row)"
                        >删除</el-button
                    >
                </template>
            </el-table-column>
        </el-table>
        <el-pagination
            background
            layout="prev, pager, next"
            :total="total"
            :current-page="pageNum"
            :page-size="pageSize"
            @current-change="handleCurrentChange"
        >
        </el-pagination>
        <el-dialog title="新增" :visible.sync="addDialogVisible" width="30%">
            <el-form
                :model="addForm"
                status-icon
                label-width="100px"
                class="demo-addForm"
            >
                <el-form-item label="作者">
                    <el-input
                        v-model="addForm.name"
                        style="width: 90%"
                    ></el-input>
                </el-form-item>
            </el-form>
            <span slot="footer" class="dialog-footer">
                <el-button type="primary" @click="sureAdd">确 定</el-button>
                <el-button @click="addDialogVisible = false">取 消</el-button>
            </span>
        </el-dialog>
        <el-dialog title="修改" :visible.sync="editDialogVisible" width="30%">
            <el-form
                :model="editForm"
                status-icon
                label-width="100px"
                class="demo-editForm"
            >
                <el-form-item label="作者">
                    <el-input
                        v-model="editForm.name"
                        style="width: 90%"
                    ></el-input>
                </el-form-item>
            </el-form>
            <span slot="footer" class="dialog-footer">
                <el-button type="primary" @click="sureEdit">确 定</el-button>
                <el-button @click="editDialogVisible = false">取 消</el-button>
            </span>
        </el-dialog>
    </div>
</template>

<script>
export default {
    data() {
        return {
            name: "",
            addDialogVisible: false, //新增弹窗控制
            editDialogVisible: false, //修改弹窗控制
            addForm: {},
            editForm: {},
            pageNum: 1,
            pageSize: 5,
            total: 0,
            tableData: [],
        };
    },
    mounted() {
        this.getData();
    },
    methods: {
        getData() {
            this.$axios({
                url: "/author/check",
                method: "get",
                params: {
                    pageNum: this.pageNum,
                    pageSize: this.pageSize,
                    name: this.name,
                },
            }).then((res) => {
                if (res.code === 200) {
                    this.tableData = res.results;
                    this.total = res.total;
                }
            });
        },
        handleCurrentChange(val) {
            this.pageNum = val;
            this.getData();
        },
        handleAdd() {
            this.addForm = {};
            this.addDialogVisible = true;
        },
        sureAdd() {
            this.$axios({
                url: "/author/add",
                method: "post",
                data: {
                    name: this.addForm.name,
                },
            }).then((res) => {
                console.log(res);
                if (res.code === 200) {
                    this.addDialogVisible = false;
                    this.$message({
                        type: "success",
                        message: "添加成功",
                    });
                    this.pageNum = Math.ceil(++this.total / this.pageSize);
                    this.getData();
                }
            });
        },
        handleDelete(row) {
            this.$confirm("此操作将永久删除该文件, 是否继续?", "提示", {
                confirmButtonText: "确定",
                cancelButtonText: "取消",
                type: "warning",
            })
                .then(() => {
                    this.$axios({
                        url: "/author/delete",
                        method: "delete",
                        data: {
                            id: row.id,
                        },
                    }).then((res) => {
                        if (res.code === 200) {
                            this.$message({
                                type: "success",
                                message: "删除成功!",
                            });
                            this.pageNum = 1;
                            this.getData();
                        }
                    });
                })
                .catch(() => {
                    this.$message({
                        type: "info",
                        message: "已取消删除",
                    });
                });
        },
        handleEdit(row) {
            this.editForm = { ...row };
            this.editDialogVisible = true;
        },
        sureEdit() {
            this.$axios({
                url: "/author/edit",
                method: "put",
                data: {
                    id: this.editForm.id,
                    name: this.editForm.name,
                },
            }).then((res) => {
                console.log(res);
                if (res.code === 200) {
                    this.editDialogVisible = false;
                    this.$message({
                        type: "success",
                        message: "修改成功",
                    });
                    this.getData();
                } else {
                    this.$message({
                        type: "error",
                        message: res.data,
                    });
                }
            });
        },
        search() {
            this.pageNum = 1;
            this.getData();
        },
    },
};
</script>

<style lang="scss">
.line {
    text-align: center;
}
.wrap {
    display: flex;
    justify-content: space-between;
    .wrap_content {
        display: flex;
        input {
            border-top-right-radius: 0px;
            border-bottom-right-radius: 0px;
        }
        button {
            border-top-left-radius: 0px;
            border-bottom-left-radius: 0px;
            border-left: 0px;
        }
    }
}

.avatar-uploader .el-upload {
    border: 1px dashed #d9d9d9;
    border-radius: 6px;
    cursor: pointer;
    position: relative;
    overflow: hidden;
}
.avatar-uploader .el-upload:hover {
    border-color: #409eff;
}
.avatar-uploader-icon {
    font-size: 28px;
    color: #8c939d;
    width: 100px;
    height: 100px;
    line-height: 100px;
    text-align: center;
}
.avatar {
    width: 100px;
    height: 100px;
    display: block;
}
.el-message-box__btns {
    padding: 5px 15px 0;
    display: flex;
    flex-direction: row-reverse;
    gap: 10px;
}
</style>
